#!/bin/bash
# Generate dev/CODEMAP.index.md from src/*.sh — the drift-prone function->module:line
# index, regenerated wholesale so it can never be mislabeled by hand (see
# dev/features/make-codemap.md). Modules are passed in as arguments by the Makefile
# (`$(MODULES)`) — never globbed here, so a stray file in src/ cannot reorder the index.
#
#   Usage: dev/codemap.sh <module.sh> [module.sh ...]
#
# Emits the index to stdout. The Makefile redirects it to dev/CODEMAP.index.md and
# `make check-codemap` fails if the committed copy is stale.

set -euo pipefail

# Literal `()` — escaped because we grep with -E (ERE), where bare () is a group.
FUNC_RE='^[a-z_][a-z0-9_]*\(\)'
OUT_FILE="dev/CODEMAP.index.md"

if [ "$#" -eq 0 ]; then
    echo "codemap.sh: no modules given (expected \$(MODULES))" >&2
    exit 1
fi

# --- Sanity: total emitted must equal a raw grep over the same files -----------
expected_total=0
for m in "$@"; do
    [ -f "$m" ] || { echo "codemap.sh: module not found: $m" >&2; exit 1; }
    c=$(grep -cE "$FUNC_RE" "$m" 2>/dev/null) || true; c=${c:-0}
    expected_total=$((expected_total + c))
done

# --- Regression guard: a module that had functions must not silently go to 0 ---
# (NOT "every module > 0" — 00-defaults/20-config/90-dispatch are legitimately 0.)
# Baseline per-module counts come from the currently committed index (if any),
# read on demand by baseline_count_for() — no associative arrays (macOS bash 3.2).
baseline_count_for() {
    # $1 = module path. Count function rows under its `### `$mod`` section in OUT_FILE.
    [ -f "$OUT_FILE" ] || { echo 0; return; }
    awk -v mod="### \`$1\`" '
        $0 == mod { inside = 1; next }
        /^### `/   { inside = 0 }
        inside && /^\| `/ { n++ }
        END { print n + 0 }
    ' "$OUT_FILE"
}

# --- Body generation -----------------------------------------------------------
by_module=""
flat=""
emitted_total=0
for m in "$@"; do
    by_module+=$'\n'"### \`$m\`"$'\n'
    rows=$(grep -nE "$FUNC_RE" "$m" || true)
    if [ -z "$rows" ]; then
        by_module+=$'\n'"_(no function definitions)_"$'\n'
        # Regression check: this module is empty now — was it non-empty in the baseline?
        prev=$(baseline_count_for "$m")
        if [ "$prev" -gt 0 ]; then
            echo "codemap.sh: REGRESSION — '$m' now has 0 functions but the committed index had $prev." >&2
            echo "codemap.sh: a broken grep pattern or a renamed-away module must not silently empty the index." >&2
            exit 1
        fi
        continue
    fi
    by_module+=$'\n'"| Function | Line |"$'\n'"|---|---|"$'\n'
    while IFS=: read -r lineno def; do
        fn=${def%%()*}
        by_module+="| \`$fn\` | $lineno |"$'\n'
        flat+="$fn|$m:$lineno"$'\n'
        emitted_total=$((emitted_total + 1))
    done <<< "$rows"
done

if [ "$emitted_total" -ne "$expected_total" ]; then
    echo "codemap.sh: count mismatch — emitted $emitted_total, grep expected $expected_total (broken pattern?)." >&2
    exit 1
fi

# --- Output --------------------------------------------------------------------
cat <<'HEADER'
# claude-mux Function Index (generated)

<!-- GENERATED by `make codemap` from src/*.sh — DO NOT EDIT BY HAND.
     Run `make codemap` after adding/renaming/moving/removing a function.
     `make check-codemap` (and the pre-commit hook + CI) fail if this is stale. -->

Authoritative mapping of every function to `module:within-module-line`. Locations are
src-derived, so a module label here can never be mistyped. Function **purposes and
signatures** live in `dev/CODEMAP.md` (human-owned prose); this file owns only the
mechanical index. Absolute built line = within-module line + the module's offset (see
`dev/CODEMAP.md` → Source Layout for offsets).
HEADER

printf '\n## Functions by module\n%s' "$by_module"

printf '\n## Function index (alphabetical)\n\n| Function | Location |\n|---|---|\n'
LC_ALL=C sort <<< "$flat" | while IFS='|' read -r fn loc; do
    [ -n "$fn" ] || continue
    printf '| `%s` | `%s` |\n' "$fn" "$loc"
done
