#!/bin/bash
# Generate dev/features/INDEX.md — the build queue, projected from each feature doc's
# frontmatter (see dev/features/make-codemap.md). Unlike the CODEMAP index (a projection
# of ground-truth src/), this projects author-asserted `lifecycle:` opinions; it guards
# only that INDEX.md matches the frontmatter, and gives a post-clear session a one-glance
# build queue. Emits to stdout; the Makefile redirects to dev/features/INDEX.md and
# `make check-features-index` fails if the committed copy is stale.
#
#   Usage: dev/features-index.sh   (scans dev/features/*.md)

set -euo pipefail

DIR="dev/features"
# Controlled vocab — display order is the build-priority order.
LIFECYCLE_ORDER="ready building designing idea shelved superseded shipped"
KINDS="feature investigation"

frontmatter_value() {
    # $1 = file, $2 = key. Echo the value from the first ---...--- block, or empty.
    awk -v key="$2" '
        NR == 1 && $0 != "---" { exit }       # no frontmatter block at all
        NR == 1 { infm = 1; next }
        infm && $0 == "---" { exit }
        infm {
            line = $0
            sub(/:.*/, "", line)
            if (line == key) {
                val = $0
                sub(/^[^:]*:[ \t]*/, "", val)
                print val
                exit
            }
        }
    ' "$1"
}

in_list() { case " $2 " in *" $1 "*) return 0;; *) return 1;; esac; }

# --- Collect + validate rows ---------------------------------------------------
# Each kept row stored as a single line: lifecycle<TAB>feature<TAB>md (for sort).
rows=""
fail=0
for f in "$DIR"/*.md; do
    case "$f" in
        *-tests.md) continue;;                        # test plans: excluded by glob FIRST
        "$DIR"/INDEX.md) continue;;                   # our own generated output
    esac
    base=$(basename "$f")

    kind=$(frontmatter_value "$f" kind)
    [ -n "$kind" ] || kind="feature"                  # default kind
    if ! in_list "$kind" "$KINDS"; then
        echo "features-index: $base — unknown kind: '$kind' (allowed: $KINDS)" >&2
        fail=1; continue
    fi
    [ "$kind" = "investigation" ] && continue         # analysis-only: excluded BEFORE lifecycle check

    feature=$(frontmatter_value "$f" feature)
    [ -n "$feature" ] || feature="${base%.md}"
    lifecycle=$(frontmatter_value "$f" lifecycle)
    if [ -z "$lifecycle" ]; then
        echo "features-index: $base — kind: feature is missing a 'lifecycle:' (one of: $LIFECYCLE_ORDER)" >&2
        fail=1; continue
    fi
    if ! in_list "$lifecycle" "$LIFECYCLE_ORDER"; then
        echo "features-index: $base — unknown lifecycle: '$lifecycle' (one of: $LIFECYCLE_ORDER)" >&2
        fail=1; continue
    fi

    tv=$(frontmatter_value "$f" target_version)
    sev=$(frontmatter_value "$f" severity)
    st=$(frontmatter_value "$f" status)
    # Escape `|` (would break the markdown table) and cap free-text length so a
    # paragraph-shaped status/target doesn't blow out the row.
    # Strip newlines AND tabs (tab is our `rows` field separator; an embedded tab
    # would split the row into phantom fields downstream) and escape table pipes.
    md_cell() { printf '%s' "$1" | tr '\n\t' '  ' | sed -e 's/  */ /g' -e 's/|/\\|/g'; }
    tv=$(md_cell "$tv"); sev=$(md_cell "$sev"); st=$(md_cell "$st")
    [ ${#tv} -gt 60 ] && tv="${tv:0:57}..."
    [ ${#st} -gt 90 ] && st="${st:0:87}..."
    [ ${#sev} -gt 90 ] && sev="${sev:0:87}..."
    [ -n "$tv" ] || tv="—"; [ -n "$sev" ] || sev="—"; [ -n "$st" ] || st="—"

    rows+="$lifecycle	$feature	| \`$feature\` | $lifecycle | $tv | $st | $sev | [$base]($base) |"$'\n'
done

[ "$fail" -eq 0 ] || { echo "features-index: validation failed — fix the frontmatter above." >&2; exit 1; }

# --- Output --------------------------------------------------------------------
cat <<'HEADER'
# claude-mux Feature Build Queue (generated)

<!-- GENERATED by `make features-index` from dev/features/*.md frontmatter — DO NOT EDIT.
     Run `make features-index` after adding a feature doc or changing its lifecycle/kind.
     `make check-features-index` (pre-commit + CI) fails if this is stale. -->

Projection of each feature doc's `lifecycle:`. This reflects the **declared** state, not
verified reality (a doc can claim `ready` before it is). `kind: investigation` docs and
`*-tests.md` plans are excluded. Grouped by lifecycle (build-priority order), then by name.
HEADER

TAB=$(printf '\t')
for lc in $LIFECYCLE_ORDER; do
    # Filter to this lifecycle, sort by feature (field 2), then drop the two key
    # columns with cut (tab-delimited; the row markdown itself contains no tabs).
    group=$(printf '%s' "$rows" | awk -F'\t' -v lc="$lc" '$1 == lc' \
            | LC_ALL=C sort -t"$TAB" -k2,2 | cut -d"$TAB" -f3-)
    [ -n "$group" ] || continue
    printf '\n## %s\n\n| Feature | Lifecycle | Target | Status | Severity | Doc |\n|---|---|---|---|---|---|\n' "$lc"
    printf '%s\n' "$group"
done
